# ----
# Site

title: UManitoba CSSA
url: "/"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"
snipcart_currency: "cad"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: UManitoba Computer Science Students' Association
author:
  name: UManitoba CSSA
  email: umanitobacssa@gmail.com
  twitter: umcssa # twitter username without the @ symbol
  phone: "+1 23456789"
social:
  name: UManitoba Cssa
  links:
    - https://github.com/

# -----
# Build
timezone: Etc/UTC

collections:
  staff_members:
    output: false
  products:
    output: true
  resources:
    output: false

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
